on:
  pull_request:
    branches: [main]
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      #checks out repository
      - uses: actions/checkout@v4
      - name: setupNode
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install --immutable
      - name: build project
        run: yarn run build
      - name: test
        run: yarn run jest
